services:
  postgres:
    image: postgres:14.18-bookworm
    environment:
      POSTGRES_USER: devUser
      POSTGRES_PASSWORD: DontUseThisPassword!
      POSTGRES_DB: usermgmt
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
  quarkus:
    build: .
    ports:
      - "8080:8080"
    environment:
      QUARKUS_PROFILE: dev
      QUARKUS_DEV_UI_ENABLED: "true"
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgres:5432/usermgmt"
      QUARKUS_DATASOURCE_USERNAME: "devUser"
      QUARKUS_DATASOURCE_PASSWORD: "DontUseThisPassword!"
      QUARKUS_REDIS_HOSTS: "redis://redis:6379"
    depends_on:
      - postgres
      - redis
volumes:
  postgres_data: {}
  redis_data: {}